# Generated by Django 4.2.4 on 2023-08-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='file_url',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='todos/images'),
        ),
        migrations.AddField(
            model_name='todo',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
