# Generated by Django 4.2.4 on 2023-08-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_file_url_todo_image_todo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='file_url',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(null=True, upload_to='todos/images'),
        ),
    ]
