# Generated by Django 4.2.4 on 2023-08-31 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_file_url_alter_todo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='important',
        ),
    ]
