# Generated by Django 4.2.4 on 2023-09-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_todo_date_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='important',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
