# Generated by Django 4.2.4 on 2023-09-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_todo_image_alter_todo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(null=True, upload_to='todos/images'),
        ),
    ]
