# Generated by Django 4.2.4 on 2023-09-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_todo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='image',
        ),
    ]
